### ISSUE TITLE
이상형 월드컵 사이트 이름 (한글ver)

### ISSUE THREAD

**Issue by alstj003** [Awant1234/OSS#16]
1. "월드컵의 정석"
    - 이상형 월드컵의 정석처럼 완벽한 선택을 제공한다는 느낌.

2. "픽플레이(PickPlay)"
    - 이상형을 고르는(pick) 재미를 즐기는(play) 곳이라는 의미.

3. "당신의 선택은?"
    - 직관적이면서도 궁금증을 유발하는 제목.

4. "월드컵 아레나"
    - 이상형들의 대결이 펼쳐지는 경기장 같은 느낌.

5. "이상픽"
    - "이상형"과 "픽"의 합성어로 간단하면서도 센스있음.

6. "이상형 리그"
    - 월드컵 대신 리그라는 단어로 재미를 더함.

7. "뭐고르Cup"
    - "뭐 고를까?"와 월드컵의 합성어로 귀엽고 친근한 느낌.

8. "픽탑(PickTop)"
    - 이상형 중에서 최상의(top) 선택을 골라낸다는 의미.

9. "마음의 선택"
   - 이상형 선택이 감정적이라는 점을 강조.

10. "최애찾기"
    - 내가 가장 좋아하는 것을 찾아가는 여정이라는 뜻.

**Comment by jinsumin81** [comment]
뭐고르Cup 재치있고 좋은 것 같네용

**Comment by wamong** [comment]
저는 픽탑(Pick Top)이요

**Comment by JONGBOK1** [comment]
10번 "최애찾기" 좋네요^_^

**Comment by jojeongin313** [comment]
저는 3번 "당신의 선택은?"이 베이직하고 좋은것 같아요

**Comment by alstj003** [comment]
저는 개인적으로 픽플레이 마음에 듭니다

**Comment by kikimiya0606** [comment]
픽플레이 굿이네요

**Comment by soon15** [comment]
픽플레이 좋은데잉
