### ISSUE TITLE
이상형 월드컵 만들기 프로그램 진행 현황

### ISSUE THREAD

**Issue by wamong** [Awant1234/OSS#17]
# 1. 이상형 월드컵 코드부터 짜보기
import random
============================================
# 후보 리스트 (예시: 연예인 이상형 월드컵)
candidates = [
    "아이유", "지민", "박보검", "송중기", "김태희", "수지", "전지현", "김연아",
    "정해인", "박서준", "이민호", "한효주", "유인나", "강다니엘", "류준열", "김고은"
]

# 후보 리스트 셔플 (순서 랜덤화)
random.shuffle(candidates)

# 이상형 월드컵 진행
def run_tournament(candidates):
    round_num = 1
    while len(candidates) > 1:
        print(f"\n---- {round_num}라운드 ----")
        next_round_candidates = []

        # 대진표 만들기 (1:1 비교)
        for i in range(0, len(candidates), 2):
            if i + 1 < len(candidates):  # 짝이 맞는 경우
                print(f"{candidates[i]} vs {candidates[i+1]}")
                choice = input("누구를 선택할까요? (1 또는 2): ")

                if choice == '1':
                    next_round_candidates.append(candidates[i])
                elif choice == '2':
                    next_round_candidates.append(candidates[i+1])
                else:
                    print("잘못된 입력입니다. 다시 선택하세요.")
                    continue
            else:  # 홀수일 경우 마지막 하나는 자동으로 승리
                next_round_candidates.append(candidates[i])

        # 다음 라운드 진출 후보
        candidates = next_round_candidates
        round_num += 1

    print(f"\n최종 승자는 {candidates[0]}입니다!")

# 게임 시작
print("이상형 월드컵을 시작합니다!")
run_tournament(candidates)
============================================
![스크린샷 2024-11-30 135458](https://github.com/user-attachments/assets/bdde554f-3039-4e73-97ab-063f03cc74eb)

**Comment by wamong** [comment]
# 2. 추가적으로 사용자가 이상형 월드컵을 만들수있는 프로그램 기본틀
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk

# 후보 리스트를 담을 변수 (이름과 사진)
candidates = []
round_number = 1

# 이미지 업로드 함수
def upload_image():
    file_path = filedialog.askopenfilename(title="이미지 파일 선택", filetypes=[("Image files", "*.jpg;*.jpeg;*.png")])
    if file_path:
        image = Image.open(file_path)
        image.thumbnail((200, 200))  # 이미지 크기 조정
        return ImageTk.PhotoImage(image)
    return None

# 후보 추가 함수
def add_candidate():
    name = name_entry.get()
    image = upload_image()
    if name and image:
        candidates.append((name, image))
        listbox.insert(tk.END, name)  # 후보 리스트 박스에 이름 추가
        name_entry.delete(0, tk.END)  # 이름 입력란 초기화

# 대진표 시작
def start_tournament():
    global round_number
    round_number = 1
    if len(candidates) < 2:
        result_label.config(text="후보가 부족합니다!")
        return
    next_round_candidates = [candidates[i] for i in range(len(candidates))]
    run_round(next_round_candidates)

# 라운드 진행 함수
def run_round(candidates_in_round):
    global round_number
    if len(candidates_in_round) == 1:
        result_label.config(text=f"최종 승자: {candidates_in_round[0][0]}")
        return
    if len(candidates_in_round) % 2 != 0:
        candidates_in_round.append(candidates_in_round[-1])  # 홀수일 때 자동 승자 처리

    # 1:1 대결
    round_display.config(text=f"{round_number}라운드")
    candidate1_name, candidate1_image = candidates_in_round[0]
    candidate2_name, candidate2_image = candidates_in_round[1]
    
    # 이미지 및 이름 표시
    candidate1_label.config(image=candidate1_image, text=candidate1_name, compound="top")
    candidate2_label.config(image=candidate2_image, text=candidate2_name, compound="top")
    
    # 버튼 클릭 시 승자 선택
    def select_winner(winner):
        nonlocal candidates_in_round
        if winner == 1:
            next_round_candidates = candidates_in_round[::2]  # 1번 승자
        else:
            next_round_candidates = candidates_in_round[1::2]  # 2번 승자
        round_number += 1
        run_round(next_round_candidates)

    button1 = tk.Button(window, text=f"{candidate1_name} 승자", command=lambda: select_winner(1))
    button2 = tk.Button(window, text=f"{candidate2_name} 승자", command=lambda: select_winner(2))
    
    button1.pack()
    button2.pack()

# GUI 설정
window = tk.Tk()
window.title("이상형 월드컵 소프트웨어")

# 후보 추가 UI
name_label = tk.Label(window, text="후보 이름 입력")
name_label.pack()
name_entry = tk.Entry(window)
name_entry.pack()

add_button = tk.Button(window, text="후보 추가", command=add_candidate)
add_button.pack()

# 후보 리스트
listbox = tk.Listbox(window)
listbox.pack()

# 대진표 시작
start_button = tk.Button(window, text="대진표 시작", command=start_tournament)
start_button.pack()

# 라운드 표시
round_display = tk.Label(window, text="0라운드")
round_display.pack()

# 결과 라벨
result_label = tk.Label(window, text="")
result_label.pack()

# 후보자 이미지 표시
candidate1_label = tk.Label(window)
candidate1_label.pack(side=tk.LEFT, padx=20)

candidate2_label = tk.Label(window)
candidate2_label.pack(side=tk.LEFT, padx=20)

window.mainloop()

![스크린샷 2024-11-30 135540](https://github.com/user-attachments/assets/dcace11a-1c93-49a1-8b41-14c0d349a0bc)

**Comment by wamong** [comment]
# 3. 이후 단계적으로 기능및 인터페이스 추가 예정.
1) 1. 4~64강 라운드 선택 기능
2) 사진수가 라운드에 필요한 사진수를 초과시, 걸러주는 코드
3) 프로그램의 기본윈도우 크기 조정
4) 제목 설정칸 추가
5) 저장과 수정 기능 추가
6) 인터페이스에 나타낼 목록기능, 불러오기 추가
7) 사진 추가시 시각적 표시 및 이름 설정목록 추가
8) 다량의 사진을 한번에 추가
9) 각 목록들에 스크롤바 및 마우스 휠스크롤 기능 추가
10) 각각의 버튼, 목록 위치 정렬

**Comment by wamong** [comment]
# 현 진행 상황
=> 후보 저장 버튼 과 스크롤바가 서로 한쪽을 구현하면 한쪽이 사라짐

import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
from PIL import Image, ImageTk
import random

# 후보 리스트를 담을 변수
candidates = []
selected_images = []

# 이미지 업로드 함수
def upload_images():
    file_paths = filedialog.askopenfilenames(title="여러 이미지 파일 선택", filetypes=[("Image files", "*.jpg;*.jpeg;*.png")])
    if file_paths:
        for file_path in file_paths:
            image = Image.open(file_path)
            image.thumbnail((200, 200))  # 이미지 크기 조정
            image_tk = ImageTk.PhotoImage(image)
            selected_images.append({'image': image_tk, 'image_path': file_path, 'name': ''})
        update_selected_images()

# 선택된 이미지 목록 업데이트
def update_selected_images():
    # 기존에 추가된 위젯들을 삭제
    for widget in selected_image_canvas.winfo_children():
        widget.destroy()

    # 새로 추가된 사진과 이름 입력란
    for image in selected_images:
        frame = tk.Frame(selected_image_canvas)
        frame.pack(pady=10)

        label_image = tk.Label(frame, image=image['image'])
        label_image.image = image['image']  # 이미지 참조 유지
        label_image.pack(side=tk.LEFT)

        # 이름을 입력할 Entry 위젯 추가
        name_entry = tk.Entry(frame, font=("Arial", 12))
        name_entry.pack(side=tk.LEFT, padx=10)
        image['name_entry'] = name_entry  # 이미지와 함께 이름 입력란 참조 저장

    selected_image_canvas.update_idletasks()
    selected_image_canvas.config(scrollregion=selected_image_canvas.bbox("all"))  # 스크롤 영역 업데이트

# 후보 저장 함수
def save_candidate():
    # 후보가 이름을 입력한 경우, 이미지와 함께 저장
    for image in selected_images:
        name = image['name_entry'].get()  # 각 이미지 옆의 이름 입력란에서 이름 가져오기
        if name:
            candidates.append({'name': name, 'image': image['image'], 'image_path': image['image_path']})
            saved_candidates_listbox.insert(tk.END, f"{len(candidates)}. {name}")  # 후보 목록에 번호와 이름 추가
        else:
            messagebox.showwarning("입력 오류", "모든 후보에 대해 이름을 입력해주세요.")  # 이름 입력을 하지 않은 경우
            return  # 이름을 입력하지 않으면 저장하지 않도록

    selected_images.clear()  # 저장 후 이미지 비우기
    update_selected_images()  # 오른쪽 구역 이미지 지우기

# GUI 설정
window = tk.Tk()
window.title("이상형 월드컵 소프트웨어")
window.geometry("1200x800")

# 화면을 3개 구역으로 나누기 위한 PanedWindow 위젯 사용
paned_window = tk.PanedWindow(window, orient="horizontal")
paned_window.pack(fill=tk.BOTH, expand=True)

# 왼쪽 구역
left_frame = tk.Frame(paned_window, bg="lightgray")
paned_window.add(left_frame)
paned_window.paneconfig(left_frame, minsize=400)  # 왼쪽 구역 최소 크기 설정

# 중앙 구역
center_frame = tk.Frame(paned_window)
paned_window.add(center_frame)
paned_window.paneconfig(center_frame, minsize=400)  # 중앙 구역 최소 크기 설정

# 오른쪽 구역
right_frame = tk.Frame(paned_window)
paned_window.add(right_frame)
paned_window.paneconfig(right_frame, minsize=400)  # 오른쪽 구역 최소 크기 설정

# 왼쪽 구역 상단: 저장된 이상형 월드컵 목록
saved_label = tk.Label(left_frame, text="저장된 이상형 월드컵 목록", font=("Arial", 14))
saved_label.pack(pady=10)

saved_photos_listbox = tk.Listbox(left_frame, height=15, width=30, font=("Arial", 12))
saved_photos_listbox.pack(padx=20, pady=10)

# 왼쪽 구역 하단: 저장된 후보 목록
saved_candidates_label = tk.Label(left_frame, text="저장된 후보 목록", font=("Arial", 14))
saved_candidates_label.pack(pady=10)

saved_candidates_listbox = tk.Listbox(left_frame, height=15, width=30, font=("Arial", 12))
saved_candidates_listbox.pack(padx=20, pady=10)

# 중앙 구역
title_label = tk.Label(center_frame, text="대회 타이틀 입력", font=("Arial", 14))
title_label.pack(pady=10)

title_entry = tk.Entry(center_frame, font=("Arial", 12))
title_entry.pack(pady=5)

# 후보 이미지 추가
add_button = tk.Button(center_frame, text="여러 후보 이미지 추가", command=upload_images, font=("Arial", 14))
add_button.pack(pady=10)

# 대회 시작 버튼
start_button = tk.Button(center_frame, text="대회 시작", font=("Arial", 14))
start_button.pack(pady=10)

# 오른쪽 구역: 선택한 후보 이미지들 및 이름 입력
right_label = tk.Label(right_frame, text="선택된 후보", font=("Arial", 14))
right_label.pack(pady=10)

# 후보 이미지 및 이름 입력 프레임
selected_image_canvas = tk.Canvas(right_frame)
selected_image_canvas.pack(pady=10, fill=tk.BOTH, expand=True)

# 스크롤바 추가
scrollbar = tk.Scrollbar(right_frame, orient="vertical", command=selected_image_canvas.yview)
scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
selected_image_canvas.config(yscrollcommand=scrollbar.set)

# 후보 저장 버튼
save_candidate_button = tk.Button(right_frame, text="후보 저장", command=save_candidate, font=("Arial", 14))
save_candidate_button.pack(pady=10)

# 실행
window.mainloop()

**Comment by Awant1234** [comment]
문제점만 정리해서 다시 올려주실 수 있나요?

**Comment by wamong** [comment]
4. 현 문제점.  대부분 cahtGPT에게 의존하다보니
=> 단계별로 버튼과 기능을 추가중인데 한가지 기능이 들어가면 한가지가 빠짐

-> 후보 저장 버튼을 만들면 스크롤바가 제대로 구현되지 않음.
-> 후보 저장버튼과 스크롤 바가 생성이 되면 다른 기능이 사라짐
    ( 라운드 수 선택 라이오 버튼 등)

그래서 해결 방안으로 각각 구현된 코드들을 해석해서 수동으로 합치는 중

**Comment by wamong** [comment]
5. 현재 이 틀에서 스크롤바랑 세부 기능 버튼들을 추가할것.
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
from PIL import Image, ImageTk
import random

# 후보 리스트를 담을 변수
candidates = []
selected_images = []

# 이미지 업로드 함수
def upload_images():
    file_paths = filedialog.askopenfilenames(title="여러 이미지 파일 선택", filetypes=[("Image files", "*.jpg;*.jpeg;*.png")])
    if file_paths:
        for file_path in file_paths:
            image = Image.open(file_path)
            image.thumbnail((200, 200))  # 이미지 크기 조정
            image_tk = ImageTk.PhotoImage(image)
            selected_images.append({'image': image_tk, 'image_path': file_path, 'name': ''})
        update_selected_images()

# 선택된 이미지 목록 업데이트
def update_selected_images():
    # 기존에 추가된 위젯들을 삭제
    for widget in selected_image_canvas.winfo_children():
        widget.destroy()

    # 새로 추가된 사진과 이름 입력란
    for image in selected_images:
        frame = tk.Frame(selected_image_canvas)
        frame.pack(pady=10)

        label_image = tk.Label(frame, image=image['image'])
        label_image.image = image['image']  # 이미지 참조 유지
        label_image.pack(side=tk.LEFT)

        # 이름을 입력할 Entry 위젯 추가
        name_entry = tk.Entry(frame, font=("Arial", 12))
        name_entry.pack(side=tk.LEFT, padx=10)
        image['name_entry'] = name_entry  # 이미지와 함께 이름 입력란 참조 저장

    selected_image_canvas.update_idletasks()
    selected_image_canvas.config(scrollregion=selected_image_canvas.bbox("all"))  # 스크롤 영역 업데이트

# 후보 저장 함수
def save_candidate():
    # 후보가 이름을 입력한 경우, 이미지와 함께 저장
    for image in selected_images:
        name = image['name_entry'].get()  # 각 이미지 옆의 이름 입력란에서 이름 가져오기
        if name:
            candidates.append({'name': name, 'image': image['image'], 'image_path': image['image_path']})
            saved_candidates_listbox.insert(tk.END, f"{len(candidates)}. {name}")  # 후보 목록에 번호와 이름 추가
        else:
            messagebox.showwarning("입력 오류", "모든 후보에 대해 이름을 입력해주세요.")  # 이름 입력을 하지 않은 경우
            return  # 이름을 입력하지 않으면 저장하지 않도록

    selected_images.clear()  # 저장 후 이미지 비우기
    update_selected_images()  # 오른쪽 구역 이미지 지우기

# GUI 설정
window = tk.Tk()
window.title("이상형 월드컵 소프트웨어")
window.geometry("1200x800")

# 화면을 3개 구역으로 나누기 위한 PanedWindow 위젯 사용
paned_window = tk.PanedWindow(window, orient="horizontal")
paned_window.pack(fill=tk.BOTH, expand=True)

# 왼쪽 구역
left_frame = tk.Frame(paned_window, bg="lightgray")
paned_window.add(left_frame)
paned_window.paneconfig(left_frame, minsize=400)  # 왼쪽 구역 최소 크기 설정

# 중앙 구역
center_frame = tk.Frame(paned_window)
paned_window.add(center_frame)
paned_window.paneconfig(center_frame, minsize=400)  # 중앙 구역 최소 크기 설정

# 오른쪽 구역
right_frame = tk.Frame(paned_window)
paned_window.add(right_frame)
paned_window.paneconfig(right_frame, minsize=400)  # 오른쪽 구역 최소 크기 설정

# 왼쪽 구역 상단: 저장된 이상형 월드컵 목록
saved_label = tk.Label(left_frame, text="저장된 이상형 월드컵 목록", font=("Arial", 14))
saved_label.pack(pady=10)

saved_photos_listbox = tk.Listbox(left_frame, height=15, width=30, font=("Arial", 12))
saved_photos_listbox.pack(padx=20, pady=10)

# 왼쪽 구역 하단: 저장된 후보 목록
saved_candidates_label = tk.Label(left_frame, text="저장된 후보 목록", font=("Arial", 14))
saved_candidates_label.pack(pady=10)

saved_candidates_listbox = tk.Listbox(left_frame, height=15, width=30, font=("Arial", 12))
saved_candidates_listbox.pack(padx=20, pady=10)

# 중앙 구역
title_label = tk.Label(center_frame, text="대회 타이틀 입력", font=("Arial", 14))
title_label.pack(pady=10)

title_entry = tk.Entry(center_frame, font=("Arial", 12))
title_entry.pack(pady=5)

# 후보 이미지 추가
add_button = tk.Button(center_frame, text="여러 후보 이미지 추가", command=upload_images, font=("Arial", 14))
add_button.pack(pady=10)

# 대회 시작 버튼
start_button = tk.Button(center_frame, text="대회 시작", font=("Arial", 14))
start_button.pack(pady=10)

# 오른쪽 구역: 선택한 후보 이미지들 및 이름 입력
right_label = tk.Label(right_frame, text="선택된 후보", font=("Arial", 14))
right_label.pack(pady=10)

# 후보 이미지 및 이름 입력 프레임
selected_image_canvas = tk.Canvas(right_frame)
selected_image_canvas.pack(pady=10, fill=tk.BOTH, expand=True)

# 스크롤바 추가
scrollbar = tk.Scrollbar(right_frame, orient="vertical", command=selected_image_canvas.yview)
scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
selected_image_canvas.config(yscrollcommand=scrollbar.set)

# 후보 저장 버튼
save_candidate_button = tk.Button(right_frame, text="후보 저장", command=save_candidate, font=("Arial", 14))
save_candidate_button.pack(pady=10)

# 실행
window.mainloop()
