### ISSUE TITLE
6 이상형 월드컵 생성 툴 제작

### ISSUE THREAD

**Issue by kikimiya0606** [Awant1234/OSS#76]
![image](https://github.com/user-attachments/assets/f13a421b-af3b-41cb-b324-22c4a48bb569)

**Comment by kikimiya0606** [comment]
![image](https://github.com/user-attachments/assets/c19aa0b9-103f-43d3-9da9-3c48d905d8da)

파일 선택 후 후보 저장 누르면 보이는 페이지

**Comment by kikimiya0606** [comment]
![image](https://github.com/user-attachments/assets/21411aa9-0819-4690-b7d1-397ce8371025)

후보 등록 후 대회 이름 지정하는 페이지

**Comment by kikimiya0606** [comment]
![image](https://github.com/user-attachments/assets/96674085-1b36-43e9-aef3-c2b0b39a1d8b)

**Comment by kikimiya0606** [comment]
![image](https://github.com/user-attachments/assets/a4c2a15a-a24d-465e-8b44-bc9c64ed124e)

선택 후 최종 우승 페이지

**Comment by kikimiya0606** [comment]
![image](https://github.com/user-attachments/assets/7dbdc7d0-523e-4f7d-a077-2181792e7f8c)

최종 디자인

**Comment by kikimiya0606** [comment]
++ 추가해야 될 점

1. 메인 화면, 마이페이지와 동일한 테마 적용 (위에 배너? 탭? 부분)
2. 실제 이상형 월드컵처럼 양쪽에 꽉 차는 사진 사이즈로 적용 (이름도 사진 안에 들어가게 하얀색으로 큰 글씨 ㄱ)
3. 대회 이름 저장 페이지에서 대회 저장까지 누르면 본인 마이페이지에 연동되는 시스템 구현

**Comment by Awant1234** [comment]
그리고 후보 등록하는거 사진 드래그해서 한번에 올리는 방법 말곤 여러개 올릴 수가 없어서 일단..수정해볼게요

**Comment by kikimiya0606** [comment]
그게 뭔 얘기인지 모르겠어용 그냥 컨트롤 해서 하나씩 선택해서 여러 개 올릴 수도 있자나여

**Comment by Awant1234** [comment]
수정이 어려워서 그냥 설명을 써두는걸로 ...

**Comment by JONGBOK1** [comment]
![image](https://github.com/user-attachments/assets/bedb9400-be1b-47ed-84cd-8d9f872f3863)

**Comment by JONGBOK1** [comment]
![image](https://github.com/user-attachments/assets/f2931936-065c-4077-a8c5-a7c64ace7d38)
이게 최선입니다..ㅠ

**Comment by JONGBOK1** [comment]
![image](https://github.com/user-attachments/assets/09fa5a6a-cf3b-4089-82af-cac75f0160b0)
저장이 되긴 하는데 실행이 안됩니다..

**Comment by wamong** [comment]
1.  테마 적용
- 홈, 마이페이지, 만들기 버튼위치가 css를 한참 살펴보았는데도 방법을 찾지못했음... 최대한 그 외 PICKPARADE라던가 배너 사이즈, 아래 푸터까지는 적용(푸터는 내용이 늘어나면 아래로 감)
![스크린샷 2024-12-10 033304](https://github.com/user-attachments/assets/d9d9025f-8dd2-4ca2-94cd-a8ddcaa14152)

**Comment by wamong** [comment]
2. 사진 사이즈 적용
- 사이즈를 키우는데에 성공했으나 후보 이름을 정하고 저장하는 곳까지 커지는것은 어쩔수 없었음..
![스크린샷 2024-12-10 024042](https://github.com/user-attachments/assets/6d78d251-b253-43c8-84d0-eafee360204c)
![스크린샷 2024-12-10 024053](https://github.com/user-attachments/assets/10760830-5b08-4517-8346-2f501a8cd4c2)

**Comment by wamong** [comment]
3. 마이페이지에 저장된 월드컵 목록 추가
- 실행은 가능하나 왜인지 사진이 깨짐. 그외 작동은 정상적
- 수정버튼 추가 -> 월드컵 타이틀의 이름 수정 가능
- 삭제버튼 추가 -> 해당 타이틀 삭제 가능
![스크린샷 2024-12-10 032142](https://github.com/user-attachments/assets/1b2ec1f5-ceea-4314-aa0d-18b51123dc34)

**Comment by wamong** [comment]
추가로 마이페이지에서 실행하는 월드컵은 html파일을 추가하여 만들었음
