### ISSUE TITLE
7 마이페이지

### ISSUE THREAD

**Issue by kikimiya0606** [Awant1234/OSS#77]
![image](https://github.com/user-attachments/assets/57136a2b-1df9-4a00-ba26-53bab0d4d900)

마이페이지 화면

**Comment by kikimiya0606** [comment]
++ 추가해야 될 부분

1. footer 부분 맨 아래로 이동
2. 이상형 월드컵 생성기에서 저장된 대회가 마이페이지에서 보이게 구현
2-1 된다면 지금까지 본인이 제작한 대회가 몇 개인지도 보이게 하기 (얘는 해도 되고 안 해도 되고)

**Comment by kikimiya0606** [comment]
+ 그리고 아이디 골라조 팀 아님 아이디가 그냥 rhffkwh!

**Comment by kikimiya0606** [comment]
+ 그리고 프로필 사진 src 거기에 프사.jpg 로 수정 ㄱㄱ

**Comment by jojeongin313** [comment]
넵 수정해볼게요

**Comment by Awant1234** [comment]
프사.jpg << 이건이미 수정햇지롱

**Comment by kikimiya0606** [comment]
넵 메인 화면 같은 경우에는 챗지피티가 가상 서버를 만들어 줘서 거기서 DB 구현이 된 거라 비슷하게 연동하면 될 거 같아용 그 아이디로 로그인 했다는 조건 하에

**Comment by jojeongin313** [comment]
마이페이지에 이전에 만든 이상형월드컵이 목록(링크방식)으로 보이게끔 구현코드 넣어서 올렸습니다!

**Comment by kikimiya0606** [comment]
아주 굿굿입니다요
